In [1]:
import numpy as np

# 1D, 2D, 3D
a1 = np.array([1, 2, 3, 4])
a2 = np.array([[1, 2], [3, 4]])
a3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Indexing
print(a1[0])
print(a2[0, 1])

# Slicing
print(a1[1:3])
print(a2[:, 0])  # column
print(a2[1, :])  # row

1
2
[2 3]
[1 3]
[3 4]


In [2]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)
print(x - y)
print(x * y)

print(np.mean(x))
print(np.var(x))
print(np.std(x))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
2.0
0.6666666666666666
0.816496580927726


In [3]:
# 1D + 2D
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])

print(a + b)

# scalar multiplication
print(a * 2)

# vector multiplication
print(a * b)

[[11 22]
 [13 24]]
[[2 4]
 [6 8]]
[[10 40]
 [30 80]]


In [4]:
arr = np.array([-2, -1, 0, 1, 2])

# square & cube
print(arr ** 2)
print(arr ** 3)

# replace negatives
arr[arr < 0] = 0
print(arr)

# normalize
arr = np.array([10, 20, 30])
norm = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print(norm)

[4 1 0 1 4]
[-8 -1  0  1  8]
[0 0 0 1 2]
[0.  0.5 1. ]


In [5]:
data = np.array([10, 50, 20, 80, 90, 30, 60])

# top 5
print(np.sort(data)[-5:])

# reshape for row/col
data2 = data.reshape(1, -1)

print(np.sum(data2, axis=1))
print(np.sum(data2, axis=0))

# indices > threshold
print(np.where(data > 50))

[30 50 60 80 90]
[340]
[10 50 20 80 90 30 60]
(array([3, 4, 6]),)


In [7]:
# PART B

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))      # multiplication
print(A.T)               # transpose
print(np.linalg.det(A))  # determinant

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
-2.0000000000000004


In [8]:
A = np.array([[2, 1], [1, 3]])
B = np.array([8, 13])

solution = np.linalg.solve(A, B)
print(solution)

[2.2 3.6]


In [9]:
import time

large = np.arange(1000000)

# loop
start = time.time()
total = 0
for x in large:
    total += x
print("Loop:", time.time() - start)

# numpy
start = time.time()
print("NumPy:", np.sum(large))
print("Time:", time.time() - start)

Loop: 0.39992594718933105
NumPy: 499999500000
Time: 0.0018939971923828125
